//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thuctapnhomnew
{
    using System;
    using System.Collections.Generic;
    
    public partial class khenthuong
    {
        public khenthuong()
        {
            this.thongtinkhacvenhanviens = new HashSet<thongtinkhacvenhanvien>();
        }
    
        public string ma { get; set; }
        public string noidung { get; set; }
    
        public virtual ICollection<thongtinkhacvenhanvien> thongtinkhacvenhanviens { get; set; }
    }
}
