//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thuctapnhomnew
{
    using System;
    using System.Collections.Generic;
    
    public partial class luongcoban
    {
        public luongcoban()
        {
            this.luongnhanviens = new HashSet<luongnhanvien>();
            this.luongnhanviens1 = new HashSet<luongnhanvien>();
            this.luongnhanviens2 = new HashSet<luongnhanvien>();
            this.luongnhanviens3 = new HashSet<luongnhanvien>();
        }
    
        public string ma { get; set; }
        public Nullable<double> heso { get; set; }
        public string ten { get; set; }
        public string hocvanma { get; set; }
        public Nullable<decimal> giatri { get; set; }
    
        public virtual hocvan hocvan { get; set; }
        public virtual hocvan hocvan1 { get; set; }
        public virtual hocvan hocvan2 { get; set; }
        public virtual hocvan hocvan3 { get; set; }
        public virtual ICollection<luongnhanvien> luongnhanviens { get; set; }
        public virtual ICollection<luongnhanvien> luongnhanviens1 { get; set; }
        public virtual ICollection<luongnhanvien> luongnhanviens2 { get; set; }
        public virtual ICollection<luongnhanvien> luongnhanviens3 { get; set; }
    }
}
