//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thuctapnhomnew
{
    using System;
    using System.Collections.Generic;
    
    public partial class chucvu
    {
        public chucvu()
        {
            this.nhanviens = new HashSet<nhanvien>();
            this.phucaps = new HashSet<phucap>();
        }
    
        public string ma { get; set; }
        public string ten { get; set; }
    
        public virtual ICollection<nhanvien> nhanviens { get; set; }
        public virtual ICollection<phucap> phucaps { get; set; }
    }
}
