//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thuctapnhomnew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNhanSuEntities : DbContext
    {
        public QLNhanSuEntities()
            : base("name=QLNhanSuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<baohiem> baohiems { get; set; }
        public DbSet<chucvu> chucvus { get; set; }
        public DbSet<hocvan> hocvans { get; set; }
        public DbSet<hopdonglaodongnhanvien> hopdonglaodongnhanviens { get; set; }
        public DbSet<khenthuong> khenthuongs { get; set; }
        public DbSet<kyluat> kyluats { get; set; }
        public DbSet<luongcoban> luongcobans { get; set; }
        public DbSet<luongnhanvien> luongnhanviens { get; set; }
        public DbSet<NguoiDung> NguoiDungs { get; set; }
        public DbSet<nhanvien> nhanviens { get; set; }
        public DbSet<phongban> phongbans { get; set; }
        public DbSet<phucap> phucaps { get; set; }
        public DbSet<thongtinkhacvenhanvien> thongtinkhacvenhanviens { get; set; }
    }
}
